import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import Header from "./components/header";
import { Footer, IFooterProps } from "./components/footer";
import { FC } from "react";
import getLayoutData from "@api/layout";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import ThemeContextProvider from "@/stores/theme";
import styles from "./page.module.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export interface ILayoutProps {
  footerData: IFooterProps;
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: FC<{ children: JSX.Element }> = async ({ children }) => {
  const data = await getLayoutData();

  return (
    <html lang="en">
      <ThemeContextProvider>
        <body className={inter.className}>
          <Header />
          <AntdRegistry>
            <main className={styles.main}>{children}</main>
          </AntdRegistry>
          <Footer {...data} />
          <Script id="theme-script" strategy="beforeInteractive">
            {`const item = localStorage.getItem('theme') || 'light';
            console.log('item +++++', item);
          localStorage.setItem('theme', item);
          document.getElementsByTagName('html')[0].dataset.theme = item;`}
          </Script>
        </body>
      </ThemeContextProvider>
    </html>
  );
};

export default RootLayout;
