import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import { Header } from "./components/header";
import { Footer, IFooterProps } from "./components/footer";
import { FC } from "react";
import code from "../../public/code.png";

const inter = Inter({ subsets: ["latin"] });

export interface ILayoutProps {
  footerData: IFooterProps;
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getFooterData() {
  return {
    footerData: {
      title: "Demo",
      linkList: [
        {
          title: "技术栈",
          list: [
            {
              label: "react",
            },
            {
              label: "typescript",
            },
            {
              label: "ssr",
            },
            {
              label: "nodejs",
            },
          ],
        },
        {
          title: "了解更多",
          list: [
            {
              label: "掘金",
              link: "https://juejin.cn/user/2714061017452557",
            },
            {
              label: "知乎",
              link: "https://www.zhihu.com/people/zmAboutFront",
            },
            {
              label: "csdn",
            },
          ],
        },
        {
          title: "联系我",
          list: [{ label: "微信" }, { label: "QQ" }],
        },
      ],
      qrCode: {
        image: code,
        text: "qrCode",
      },
      copyRight: "Copyright © 2022 xxx. 保留所有权利",
      siteNumber: "ICP备12345号-1",
      publicNumber: "公网安备 66666号",
    },
  };
}

const RootLayout: FC<{ children: JSX.Element }> = async ({ children }) => {
  const { footerData } = await getFooterData();

  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer {...footerData} />
      </body>
    </html>
  );
};

export default RootLayout;
