import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import { Header } from "./components/header";
import { Footer, IFooterProps } from "./components/footer";
import { FC } from "react";
import code from "../../public/code.png";

const inter = Inter({ subsets: ["latin"] });

export interface ILayoutProps {
  footerData: IFooterProps;
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getFooterData() {
  return {
    footerData: {
      title: "Demo",
      linkList: [
        {
          title: "技术栈",
          list: [
            {
              label: "react",
            },
            {
              label: "typescript",
            },
            {
              label: "ssr",
            },
            {
              label: "nodejs",
            },
          ],
        },
        {
          title: "了解更多",
          list: [
            {
              label: "掘金",
              link: "https://juejin.cn/user/2714061017452557",
            },
            {
              label: "知乎",
              link: "https://www.zhihu.com/people/zmAboutFront",
            },
            {
              label: "csdn",
            },
          ],
        },
        {
          title: "联系我",
          list: [{ label: "微信" }, { label: "QQ" }],
        },
      ],
      qrCode: {
        image: code,
        text: "qrCode",
      },
      copyRight: "Copyright © 2022 xxx. 保留所有权利",
      siteNumber: "ICP备12345号-1",
      publicNumber: "公网安备 66666号",
    },
  };
}

async function getArticleData() {
  return {
    title: "Hello SSR!",
    description: "A Demo for 《深入浅出SSR官网开发指南》",
    list: [
      {
        label: "文章1",
        info: "A test for article1",
        link: "http://localhost:3000/article/1",
      },
      {
        label: "文章2",
        info: "A test for article2",
        link: "http://localhost:3000/article/2",
      },
      {
        label: "文章3",
        info: "A test for article3",
        link: "http://localhost:3000/article/3",
      },
      {
        label: "文章4",
        info: "A test for article4",
        link: "http://localhost:3000/article/4",
      },
      {
        label: "文章5",
        info: "A test for article5",
        link: "http://localhost:3000/article/5",
      },
      {
        label: "文章6",
        info: "A test for article6",
        link: "http://localhost:3000/article/6",
      },
    ],
  };
}

const RootLayout: FC<{ children: JSX.Element }> = async ({ children }) => {
  const { footerData } = await getFooterData();
  // const articleData = await getArticleData();
  // console.log("articleData ++++", articleData);

  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer {...footerData} />
      </body>
    </html>
  );
};

export default RootLayout;
